name: Push heroku

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
          repository: slow/360noscope
          path: 360noscope

      - name: Clone repository
        run: |
          git clone https://slow:${{ secrets.GH_TOKEN }}@github.com/slow/nitro-sniper
          cd nitro-sniper

      - name: Delete files
        run: |
          cd nitro-sniper
          rm -rf .github
          rm -rf README.md
          rm -rf CHANGELOG.md
          rm -rf .git
          rm -rf .releaserc.json
          rm -rf .env
          cd ..

      - name: Set up credentials
        run: |
          git config --global user.name 'eternal'
          git config --global user.email '73202350+slow@users.noreply.github.com'
          git config --global init.defaultBranch 'main'

      - name: Generate random repo name
        run: |
          echo repoName=openssl rand -base64 12 >> $GITHUB_ENV

      - name: Commit changes & push
        run: |
          cd nitro-sniper
          git init
          git remote add origin https://github.com/slow/${{ env.repoName }}.git
          git add .
          git commit -m "Pull commit ${{ github.sha }}"
          git push --force origin
